### PR TITLE
Enhancement to package

### PR DESCRIPTION
**Pull request by HarshaDokula**
This pull request is an enhancement for the repository. 
Added a few other API calls and few descriptions here and here for better understanding of the project.

AND changed the python-jose package to pyjwt since the jwt decode.

### CODE REVIEW

**Review by asafd1 — COMMENTED** [review]
what's the reason for changing python-jose with pyjwt?

**Comment by HarshaDokula** [comment]
Screenshot 2019-06-06 at 10 22 01 PM

Sorry that I didn't mention it properly. Here is a screenshot of the error I am getting while running the program. By looking at the error, I think it's a problem in the python-Jose package (not sure) so I have changed the package to pyjwt.

**Comment by asafd1** [comment]
This is a compatibility issue with python version 3.x. Do your changes work with python 2.x? If they do I'm fine with switching

**Comment by HarshaDokula** [comment]
Hey, I am making a new pull request. I have unknowingly uploaded the .properties file to the remote so had to delete the branch and needed to create a new one to delete the history. Sorry for the inconvenience.

**Pull request closed without merging**
